// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkVV2MPahkC0KUvmiocX7jP3QKFOtPAsY',
    appId: '1:425767736830:web:6e14cf36d8b3cbf29a5caf',
    messagingSenderId: '425767736830',
    projectId: 'movie-2b033',
    authDomain: 'movie-2b033.firebaseapp.com',
    storageBucket: 'movie-2b033.firebasestorage.app',
    measurementId: 'G-Y8BR8JRBGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtWQJe2oYg25nln19Z_5q9zC8ZnobDpC4',
    appId: '1:425767736830:android:49db267d762cba789a5caf',
    messagingSenderId: '425767736830',
    projectId: 'movie-2b033',
    storageBucket: 'movie-2b033.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAlxgqenM6PN2h4-T8pTJROhC8ZBjBFXw',
    appId: '1:425767736830:ios:d79e4b64d16a0cad9a5caf',
    messagingSenderId: '425767736830',
    projectId: 'movie-2b033',
    storageBucket: 'movie-2b033.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAlxgqenM6PN2h4-T8pTJROhC8ZBjBFXw',
    appId: '1:425767736830:ios:d79e4b64d16a0cad9a5caf',
    messagingSenderId: '425767736830',
    projectId: 'movie-2b033',
    storageBucket: 'movie-2b033.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkVV2MPahkC0KUvmiocX7jP3QKFOtPAsY',
    appId: '1:425767736830:web:1ceade7ffff5df0c9a5caf',
    messagingSenderId: '425767736830',
    projectId: 'movie-2b033',
    authDomain: 'movie-2b033.firebaseapp.com',
    storageBucket: 'movie-2b033.firebasestorage.app',
    measurementId: 'G-CZDFENHEK7',
  );
}
